---
apiVersion: v2
name: forms-flow-ai
dependencies:
  - name: postgresql-ha 
    repository: https://charts.bitnami.com/bitnami
    version: 10.0.9
  - name: mongodb
    condition: mongodb.enabled 
    repository: https://charts.bitnami.com/bitnami
    version: 13.6.3
version: v2.1.5
icon: "https://raw.githubusercontent.com/AOT-Technologies/forms-flow-ai/develop/.images/logo.png"
