{{- if .Values.frontend.enabled }}
{{- if and .Values.frontend.pdb  .Values.frontend.pdb.enabled }}
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "frontend.fullname" . }}
  labels:
    {{- include "frontend.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "frontend.selectorLabels" . | nindent 6 }}
  minAvailable: {{ .Values.frontend.pdb.minAvailable }}
{{- end }}
{{- end }}
