{{- if and .Values.crunchy.enabled .Values.crunchy.pgBackRest.s3.enabled}}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{.Release.Name}}-s3-secret
type: Opaque
stringData:
  s3.conf: |-
        {{ include "crunchy.s3" . | nindent 8}}
{{- end }}
