services:
  forms-flow-web-root-config:
    container_name: forms-flow-web-root-config
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - MF_FORMSFLOW_WEB_URL=${MF_FORMSFLOW_WEB_URL}
        - MF_FORMSFLOW_NAV_URL=${MF_FORMSFLOW_NAV_URL}
        - MF_FORMSFLOW_SERVICE_URL=${MF_FORMSFLOW_SERVICE_URL}
        - MF_FORMSFLOW_ADMIN_URL=${MF_FORMSFLOW_ADMIN_URL}
        - MF_FORMSFLOW_THEME_URL=${MF_FORMSFLOW_THEME_URL}
        - NODE_ENV=${NODE_ENV}
        - ssh_prv_key=${SSH_PRV_KEY}
        - ssh_pub_key=${SSH_PUB_KEY}
    entrypoint: /bin/sh -c "/usr/share/nginx/html/config/env.sh && nginx -g 'daemon off;'"
    environment:
      - NODE_ENV=${NODE_ENV}
      - REACT_APP_API_PROJECT_URL=${FORMIO_DEFAULT_PROJECT_URL}
      - REACT_APP_API_SERVER_URL=${FORMIO_DEFAULT_PROJECT_URL}
      - REACT_APP_APPLICATION_NAME=${APPLICATION_NAME}
      - REACT_APP_BPM_URL=${BPM_API_URL}
      - REACT_APP_CUSTOM_LOGOUT_URL=${EPD_IDP_LOGOUT_URL}
      - REACT_APP_CUSTOM_MAP_URL=${EPD_CUSTOM_MAP_URL}
      - REACT_APP_CUSTOM_RESOURCE_BUNDLE_URL=${CUSTOM_RESOURCE_BUNDLE_URL}
      - REACT_APP_CUSTOM_SUBMISSION_ENABLED=${CUSTOM_SUBMISSION_ENABLED}
      - REACT_APP_CUSTOM_SUBMISSION_URL=${CUSTOM_SUBMISSION_URL}
      - REACT_APP_CUSTOM_THEME_URL=${CUSTOM_THEME_URL}
      - REACT_APP_DOCUMENT_SERVICE_URL=${DOCUMENT_SERVICE_URL}
      - REACT_APP_DRAFT_ENABLED=${DRAFT_ENABLED}
      - REACT_APP_DRAFT_POLLING_RATE=${DRAFT_POLLING_RATE}
      - REACT_APP_ENABLE_APPLICATION_ACCESS_PERMISSION_CHECK=${ENABLE_APPLICATION_ACCESS_PERMISSION_CHECK}
      - REACT_APP_ENABLE_APPLICATIONS_MODULE=${ENABLE_APPLICATIONS_MODULE}
      - REACT_APP_ENABLE_DASHBOARDS_MODULE=${ENABLE_DASHBOARDS_MODULE}
      - REACT_APP_ENABLE_FORMS_MODULE=${ENABLE_FORMS_MODULE}
      - REACT_APP_ENABLE_PROCESSES_MODULE=${ENABLE_PROCESSES_MODULE}
      - REACT_APP_ENABLE_TASKS_MODULE=${ENABLE_TASKS_MODULE}
      - REACT_APP_EXPORT_PDF_ENABLED=${EXPORT_PDF_ENABLED}
      - REACT_APP_KEYCLOAK_CLIENT=${KEYCLOAK_WEB_CLIENT_ID}
      - REACT_APP_KEYCLOAK_ENABLE_CLIENT_AUTH=${KEYCLOAK_ENABLE_CLIENT_AUTH}
      - REACT_APP_KEYCLOAK_URL_REALM=${KEYCLOAK_URL_REALM}
      - REACT_APP_KEYCLOAK_URL=${KEYCLOAK_URL}
      - REACT_APP_MT_ADMIN_BASE_URL_VERSION=${MT_ADMIN_BASE_URL_VERSION}
      - REACT_APP_MT_ADMIN_BASE_URL=${MT_ADMIN_BASE_URL}
      - REACT_APP_MULTI_TENANCY_ENABLED=${MULTI_TENANCY_ENABLED}
      - REACT_APP_PUBLIC_WORKFLOW_ENABLED=${PUBLIC_WORKFLOW_ENABLED}
      - REACT_APP_WEB_BASE_CUSTOM_URL=${WEB_BASE_CUSTOM_URL}
      - REACT_APP_WEB_BASE_URL=${FORMSFLOW_API_URL}
      - REACT_APP_WEBSOCKET_ENCRYPT_KEY=${WEBSOCKET_ENCRYPT_KEY}
    ports:
      - "3000:8080"
    tty: true
