---
version: "3.8"
networks:
  app-tier:
    driver: bridge

services:
  database:
    networks:
      - app-tier 
    container_name: database
    environment:
      POSTGRES_USER: default
      POSTGRES_PASSWORD: default
      POSTGRES_DB: default
    hostname: database
    image: postgres:12
    restart: always
    volumes:
      - /pgdata
  users:
    networks:
      - app-tier 
    container_name: users
    entrypoint:
      - "sh"
      - "-c"
      - "npm i && npm run start"
    environment:
      NODE_ENV: development
      POSTGRESQL_HOST: database
      POSTGRESQL_USER: default
      POSTGRESQL_PASSWORD: default
      POSTGRESQL_DATABASE: default
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3005"]
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 40s
    hostname: users
    image: node:14
    links:
      - database
    ports:
      - "3005:3005"
    expose:
      - 3005 
    volumes:
      - ./backend/users:/app:z
      - /app/node_modules
    working_dir: "/app"
  applications:
    networks:
      - app-tier 
    container_name: applications
    entrypoint:
      - "sh"
      - "-c"
      - "npm i && npm run start"
    environment:
      NODE_ENV: development
      POSTGRESQL_HOST: database
      POSTGRESQL_USER: default
      POSTGRESQL_PASSWORD: default
      POSTGRESQL_DATABASE: default
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3006"]
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 40s
    hostname: applications
    image: node:14
    links:
      - database
    ports:
      - "3006:3006"
    expose:
      - 3006 
    volumes:
      - ./backend/applications:/app:z
      - /app/node_modules
    working_dir: "/app"
  graphqlgateway:
    networks:
      - app-tier 
    container_name: graphqlgateway
    entrypoint:
      - "sh"
      - "-c"
      - "npm i && npm run start"
    environment:
      NODE_ENV: development
      POSTGRESQL_HOST: database
      POSTGRESQL_USER: default
      POSTGRESQL_PASSWORD: default
      POSTGRESQL_DATABASE: default
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3010"]
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 40s
    hostname: graphqlgateway
    image: node:14
    links:
      - database
    ports:
      - "3010:3010"
    depends_on:
      - "users"
      - "applications"
    volumes:
      - ./backend/gateway:/app:z
      - /app/node_modules
    working_dir: "/app"

  # backend:
  #   container_name: backend
  #   entrypoint:
  #     - "sh"
  #     - "-c"
  #     - "npm i && npm run start"
  #   environment:
  #     NODE_ENV: development
  #     POSTGRESQL_HOST: database
  #     POSTGRESQL_USER: default
  #     POSTGRESQL_PASSWORD: default
  #     POSTGRESQL_DATABASE: default
  #   healthcheck:
  #     test: ["CMD", "curl", "-f", "http://localhost:3000"]
  #     interval: 1m30s
  #     timeout: 10s
  #     retries: 3
  #     start_period: 40s
  #   hostname: backend
  #   image: node:14
  #   links:
  #     - database
  #   ports:
  #     - "3001:3000"
  #   volumes:
  #     - ./backend:/app:z
  #     - /app/node_modules
  #   working_dir: "/app"

  frontend:
    container_name: frontend
    entrypoint:
      - "sh"
      - "-c"
      - "npm i && npm run start"
    environment:      
      - WATCHPACK_POLLING=true 
      - NODE_ENV=development
      - BACKEND_URL=backend
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 40s
    hostname: frontend
    image: node:14
    links:
      - graphqlgateway
    ports:
      - "3000:3000"
      - "35729:35729"
    volumes:
      - ./frontend:/app:z
      - /app/node_modules
    working_dir: "/app"
