FROM node:16.14.0-alpine
#FROM artifacts.developer.gov.bc.ca/docker-remote/node:14.17.1-alpine

# NPM Permission Fix
RUN mkdir -p /.npm
RUN chown -R 1001:0 /.npm

# Install packages, build and keep only prod packages
WORKDIR /app

# A wildcard is used to ensure both package.json AND package-lock.json are copied
COPY package*.json ./

# Set NODE_ENV environment variable
#ENV NODE_ENV production

# Install app dependencies using the `npm ci` command instead of `npm install`
RUN npm ci

#RUN npm build

# Bundle app source
COPY . .

RUN chown -R 1001:0 
USER 1001

RUN set -x \
        && chmod -R 777 /app/

RUN apk add postgresql-client

ENTRYPOINT [ "sh", "initDB.sh" ]