FROM node:16.14.0-alpine

# Set npm cache directory
ENV NPM_CONFIG_CACHE=/home/node/.npm

# Create necessary directories with correct permissions
RUN mkdir -p /home/node/.npm/_cacache /home/node/.npm/_logs \
    && chown -R 1001:0 /home/node/.npm

# Install packages, build, and keep only prod packages
WORKDIR /app

# A wildcard is used to ensure both package.json AND package-lock.json are copied
COPY package*.json ./

# Set NODE_ENV environment variable
# ENV NODE_ENV production

# Install app dependencies using the `npm ci` command instead of `npm install`
RUN npm ci

# Bundle app source
COPY . .

# Change ownership of files to non-root user
RUN chown -R 1001:0 /app

# Switch to non-root user
USER 1001

# Install postgresql-client
RUN apk add --no-cache postgresql-client

# Define the entrypoint
ENTRYPOINT [ "sh", "initDB.sh" ]
