FROM node:16.14.0-alpine
#FROM artifacts.developer.gov.bc.ca/docker-remote/node:14.17.1-alpine
# Set npm cache directory
ENV NPM_CONFIG_CACHE=/home/node/.npm

# Install packages, build and keep only prod packages
WORKDIR /app

# A wildcard is used to ensure both package.json AND package-lock.json are copied
COPY package*.json ./

# Set NODE_ENV environment variable
#ENV NODE_ENV production

# Install app dependencies using the `npm ci` command instead of `npm install`
RUN npm ci

# Ensure ownership of .npm folder
RUN mkdir -p /home/node/.npm \
    && chown -R node:node /home/node/.npm

#RUN npm build

# Bundle app source
COPY . .

RUN set -x \
        && chmod -R 777 /app/

RUN apk add postgresql-client

ENTRYPOINT [ "sh", "initDB.sh" ]