# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
#-- global variables, can be accessed by sub-charts.
global:
  #-- the registry where the images are stored. override during runtime for other registry at global level or individual level.
  repository: ~ # provide the repo name from where images will be sourced for example bcgo
  #-- the registry where the images are stored. override during runtime for other registry at global level or individual level. default is ghcr.io
  registry: artifacts.developer.gov.bc.ca/github-docker-remote # ghcr.io for directly streaming from github container registry or "artifacts.developer.gov.bc.ca/github-docker-remote" for artifactory, or any other registry.
  #-- the tag of the image, it can be latest, 1.0.0 etc..., or the sha256 hash
  tag: ~
  #-- turn off autoscaling for the entire suite by setting this to false. default is true.
  autoscaling: true
  #-- global secrets, can be accessed by sub-charts.
  secrets:
    enabled: true
    keycloakSecret: ~
    keycloakRealm: ~
    keycloakClientID: ~
    keycloakAuthURL: ~
    persist: true
  config:
    dbName: cats # if updating this value, make sure this is updated `bitnami-pg: auth:     username: site , database: site in values-pr.yaml`
    schemaName: cats
    dbUser: ~ # either site or pr specific user.
    seed:
      enabled: false
  #-- domain of the application, it is required, apps.silver.devops.gov.bc.ca for silver cluster and apps.devops.gov.bc.ca for gold cluster
  domain: "apps.silver.devops.gov.bc.ca" # it is apps.gold.devops.gov.bc.ca for gold cluster
  #-- the database Alias gives a nice way to switch to different databases, crunchy, patroni ... etc.
  databaseAlias: postgres-crunchy
#-- the components of the application, backend.
backend:
  #-- enable or disable backend
  enabled: true
  #-- the deployment strategy, can be "Recreate" or "RollingUpdate"
  deploymentStrategy: RollingUpdate
  #-- autoscaling for the component. it is optional and is an object.
  autoscaling:
    #-- enable or disable autoscaling.
    enabled: true
    #-- the minimum number of replicas.
    minReplicas: 2
    #-- the maximum number of replicas.
    maxReplicas: 3
    #-- the target cpu utilization percentage, is from request cpu and NOT LIMIT CPU.
    targetCPUUtilizationPercentage: 80
  resources:
    requests:
      cpu: 50m
      memory: 150Mi
  #-- the service for the component. for inter namespace communication, use the service name as the hostname.
  service:
    #-- the type of the service. it can be ClusterIP, NodePort, LoadBalancer, ExternalName. ClusterIP is the default and is recommended.
    type: ClusterIP
    port: 80 # this is the service port, where it will be exposed internal to the namespace.
    targetPort: 4005 # this is container port where app listens on
  ingress:
    annotations:
      route.openshift.io/termination: "edge"
  pdb:
    enabled: true # enable it in PRODUCTION for having pod disruption budget.
    minAvailable: 1 # the minimum number of pods that must be available during the disruption budget.

frontend:
  # -- enable or disable a component deployment.
  enabled: true
  # -- the deployment strategy, can be "Recreate" or "RollingUpdate"
  deploymentStrategy: RollingUpdate

  config:
    VITE_CATS_CSSA_MANAGER_ROLE: "formsflow-reviewer/cssa-manager"

  #-- autoscaling for the component. it is optional and is an object.
  autoscaling:
    #-- enable or disable autoscaling.
    enabled: true
    #-- the minimum number of replicas.
    minReplicas: 2
    #-- the maximum number of replicas.
    maxReplicas: 3
    #-- the target cpu utilization percentage, is from request cpu and NOT LIMIT CPU.
    targetCPUUtilizationPercentage: 80
  #-- the service for the component. for inter namespace communication, use the service name as the hostname.
  service:
    #-- enable or disable the service.
    enabled: true
    #-- the type of the service. it can be ClusterIP, NodePort, LoadBalancer, ExternalName. ClusterIP is the default and is recommended.
    type: ClusterIP
    #-- the ports for the service.
    targetPort: 8080
  ingress:
    annotations:
      route.openshift.io/termination: "edge"
  pdb:
    enabled: true # enable it in PRODUCTION for having pod disruption budget.
    minAvailable: 1 # the minimum number of pods that must be available during the disruption budget.
  config:
    REACT_APP_BACKEND_API: "https://nr-epd-digital-services-test-backend.apps.silver.devops.gov.bc.ca"
    REACT_APP_AUTH_AUTHORITY: "https://epd-keycloak-test.apps.silver.devops.gov.bc.ca/auth/realms/forms-flow-ai/"
    REACT_APP_AUTH_CLIENT_ID: "site-web"
    REACT_APP_AUTH_REDIRECT_URI: "https://nr-epd-digital-services-test-frontend.apps.silver.devops.gov.bc.ca"
    REACT_APP_AUTH_LOGOUT_REDIRECT_URI: "https://logontest7.gov.bc.ca/clp-cgi/logoff.cgi?retnow=1&returl=https://epd-keycloak-test.apps.silver.devops.gov.bc.ca/auth/realms/forms-flow-ai/protocol/openid-connect/logout?post_logout_redirect_uri=https://nr-epd-digital-services-test-frontend.apps.silver.devops.gov.bc.ca/"
    REACT_APP_AUTH_RESPONSE_TYPE: "code"
    REACT_APP_AUTH_SCOPE: "openid profile"
    REACT_APP_AUTH_FILTER_PROTOCOL_CLAIMS: "true"
    REACT_APP_AUTH_LOAD_USER_INFO: "true"
    REACT_APP_AUTH_REVOKE_TOKENS_ON_SIGNOUT: "true"
    VITE_GEOCODER_API: "https://geocoder.api.gov.bc.ca"


