---
kind: Template
apiVersion: v1
metadata:
  name: "${API_NAME}-build-template"
  creationTimestamp: 
objects:
- kind: ImageStream
  apiVersion: v1
  metadata:
    name: "${API_NAME}"
- kind: BuildConfig
  apiVersion: v1
  metadata:
    name: "${API_NAME}-build"
    labels:
      app: "${API_NAME}-build"
  spec:
    completionDeadlineSeconds: 3600 # NOT WORKING?: Custom build time of 1hr, as builds are looong - STILL FAILS AFTER 30m
    resources:
      limits:
        cpu: "1500m" 
        memory: "4Gi"    
      requests:
        cpu: "500m"
        memory: "2Gi" 
    runPolicy: Serial
    source:
      type: Git
      git:
        uri: "${GIT_REPO_URL}"
        ref: "${GIT_REF}"
      contextDir: "${SOURCE_CONTEXT_DIR}"
    strategy:
      type: Docker
      dockerStrategy:
        dockerfilePath: "${DOCKER_FILE_PATH}"
    output:
      to:
        kind: ImageStreamTag
        name: "${API_NAME}:${ENV_TAG}"
parameters:
- name: API_NAME
  displayName: Name
  description: The name assigned to all of the resources defined in this template.
  required: true
  value: forms-flow-theme
- name: ENV_TAG
  displayName: Environment name
  description: The name of the environment, in build names and image stream tags
  required: true
  value: dev
- name: GIT_REPO_URL
  displayName: Git Repo URL
  description: The URL to your GIT repo.
  required: true
  value: https://github.com/bcgov/nr-epd-digital-services
- name: GIT_REF
  displayName: Git Reference
  description: The git reference or branch.
  required: true
  value: dev
- name: SOURCE_CONTEXT_DIR
  displayName: Source Context Directory
  description: The source context directory.
  required: false
  value: forms-flow-ai/forms-flow-ai-micro-front-ends/forms-flow-theme
- name: DOCKER_FILE_PATH
  displayName: Docker File Path
  description: The path to the docker file defining the build.
  required: false
  value: "Dockerfile"