# This is used to bootstrap the database.
FROM node:22-alpine

# Set npm cache directory
ENV NPM_CONFIG_CACHE=/home/node/.npm

# Install packages, build, and keep only prod packages
WORKDIR /app

# A wildcard is used to ensure both package.json AND package-lock.json are copied
COPY package*.json ./

# Install app dependencies using the `npm ci` command instead of `npm install`
RUN npm ci

# Bundle app source
COPY . .
# Install postgresql-client
RUN apk add --no-cache postgresql-client
