---
kind: Template
apiVersion: template.openshift.io/v1
metadata:
  name: "${API_NAME}-build-template"
  creationTimestamp: 
objects:
- kind: ImageStream
  apiVersion: v1
  metadata:
    name: "${API_NAME}"
- kind: BuildConfig
  apiVersion: v1
  metadata:
    name: "${API_NAME}-build"
    labels:
      app: "${API_NAME}-build"
  spec:
    runPolicy: Serial
    source:
      type: Git
      git:
        uri: "${GIT_REPO_URL}"
        ref: "${GIT_REF}"
      contextDir: "${SOURCE_CONTEXT_DIR}"
    strategy:
      type: Docker
      dockerStrategy:
        dockerfilePath: "${DOCKER_FILE_PATH}"
    output:
      to:
        kind: ImageStreamTag
        name: "${API_NAME}:latest"
parameters:
- name: API_NAME
  displayName: Name
  description: The name assigned to all of the resources defined in this template.
  required: true
  value: debezium-postgis
- name: GIT_REPO_URL
  displayName: Git Repo URL
  description: The URL to your GIT repo.
  required: true
  value: https://github.com/bcgov/nr-epd-digital-services
- name: GIT_REF
  displayName: Git Reference
  description: The git reference or branch.
  required: true
  value: dev
- name: SOURCE_CONTEXT_DIR
  displayName: Source Context Directory
  description: The source context directory.
  required: false
  value: etl/debezium-postgis/15-3.3
- name: DOCKER_FILE_PATH
  displayName: Docker File Path
  description: The path to the docker file defining the build.
  required: false
  value: "Dockerfile"
