kind: BuildConfig
apiVersion: build.openshift.io/v1
metadata:
  name: cats-backend
  namespace: e38158-tools
spec:
  runPolicy: Serial
  source:
    type: Git
    git:
      uri: 'https://github.com/bcgov/nr-epd-digital-services.git'
      ref: 'dev'
    contextDir: backend/cats
  strategy:
    type: Docker
    dockerStrategy:
      env:
      dockerfilePath: Dockerfile
  output:
    to:
      kind: ImageStreamTag
      name: 'cats-backend:dev'
  triggers:
    - type: ImageChange
      imageChange:
        from:
          kind: ImageStreamTag
          name: cats-backend-init:dev
  successfulBuildsHistoryLimit: 5
  failedBuildsHistoryLimit: 5
