apiVersion: v1
kind: Secret
metadata:
  labels:
    app: "{{ .Chart.Name }}"
  name: "{{ .Chart.Name }}"
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: ewogICJhdXRocyI6IHsKICAgICJkb2NrZXIuaW8iOiB7CiAgICAgICJ1c2VybmFtZSI6ICJ0ZXN0YWNjb3VudCIsCiAgICAgICJwYXNzd29yZCI6ICJ0ZXN0X2FjY291bnRfc2FtcGxlX2RvY2tlcmFjY291bnQiLAogICAgICAiYXV0aCI6ICJhR1ZzYkc4Z2QyOXliR1E9IgogICAgfQogIH0sCiAgImFsZyI6ICJIUzI1NiIKfQ==