apiVersion: v1
kind: Secret
metadata:
  labels:
    app: "{{ .Chart.Name }}"
  name: "{{ .Chart.Name }}"
stringData:
  FORMIO_ROOT_EMAIL: {{ index .Values "forms-flow-forms" "admin" "email" }}
  FORMIO_ROOT_PASSWORD: {{ index .Values "forms-flow-forms" "admin" "password" }}
  FORMIO_JWT_SECRET: "{{ .Release.Namespace }}-jwt-secret" 
  KEYCLOAK_CLIENTID: {{ index .Values "forms-flow-bpm" "clientid" }}
  KEYCLOAK_CLIENTSECRET: {{ index .Values "forms-flow-bpm" "clientsecret" }}
  WEB_CLIENTID: {{ index .Values "forms-flow-web" "clientid"}}
  WEBSOCKET_ENCRYPT_KEY: "{{.Values.websocket_encrypt_key}}"
  ADMIN_WEB_CLIENTID: {{ index .Values "forms-flow-web" "clientid"}}
  INSIGHT_API_KEY:  "{{.Values.insight_api_key}}"
  REDIS_PASSCODE: "{{.Values.redis_pass_code}}"
---
apiVersion: v1
kind: Secret
metadata:
  labels:
    app: {{ .Chart.Name }}-auth
  name: {{ .Chart.Name }}-auth
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ index .Values "forms-flow-auth" "imagesecret" }}
