# Only ovverride values-test.yaml if the environment is TEST with the following values as a delta:
crunchy: # enable it for TEST and PROD, for PR based pipelines simply use single postgres
  instances:
    dataVolumeClaimSpec:
      storage: 600Mi
      storageClassName: netapp-block-standard
      walStorage: 350Mi

  pgBackRest:
    backupPath: /backups/prod/cluster/version # change it for PROD, create values-prod.yaml
    s3:
      enabled: true
      retention: 7 # one week backup in object store for prod environment
      bucket: nrsiteprd
      endpoint: nrs.objectstore.gov.bc.ca
      accessKey: ~
      secretKey: ~
      fullBackupSchedule: 0 0/4 * * * # full backup every 4 hours
      incrementalBackupSchedule: 0 1,6,11,17,23 * * * * # incremental backup every 5 hours
    pvc:
      volume:
        storage: 1024Mi
  # Postgres Cluster resource values:
  pgmonitor:
    enabled: true
