---
apiVersion: v1
kind: Secret
metadata:
  labels:
    app: "{{ .Chart.Name }}"
  name: "{{ .Chart.Name }}"
stringData:
  POSTGRES_HOST_AUTH_METHOD: trust
  POSTGRES_PASSWORD: postgres
  PYTHONUNBUFFERED: "0"
  REDASH_COOKIE_SECRET: redash-selfhosted
  REDASH_LOG_LEVEL: INFO
  REDASH_REDIS_URL: "redis://redis-exporter:6379/0" # url of the redis database to connect to
  REDASH_SECRET_KEY: redash-selfhosted
  REDASH_MULTI_ORG: 'false'
  REDASH_DATABASE_PASSWORD: "{{ .Values.database.password }}"
---  
apiVersion: v1
kind: Secret
metadata:
  labels:
    app: forms-flow-ai-auth
  name: forms-flow-ai-auth
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: eyJhdXRocyI6eyJkb2NrZXIuaW8iOnsidXNlcm5hbWUiOiJhbGFucmFqdTAwNyIsInBhc3N3b3JkIjoiZGNrcl9wYXRfQ0Z3OTdJeUpmY3hpblNfQXpaOGlBcDlvSVkwIiwiYXV0aCI6IllXeGhibkpoYW5Vd01EYzZaR05yY2w5d1lYUmZRMFozT1RkSmVVcG1ZM2hwYmxOZlFYcGFPR2xCY0RsdlNWa3cifX19
