query getApplicationById($applicationId: Int!) {
  getApplicationDetailsById(id: $applicationId) {
    data {
      id
      formId
      submissionId
      receivedDate
      currentStatus {
        id
        description
      }
    }
  }
}

query getSubmissionByApplicationId($applicationId: Int!) {
  getSubmissionByApplicationId(applicationId: $applicationId) {
    message
    httpStatusCode
    success
    data {
      id
      applicationId
      chefsFormId
      chefsSubmissionId
      chefsConfirmationId
      linkedConfirmationIds
      formData
      formSchema
      receivedAt
    }
  }
}

query getApplicationStatusTypes {
  getAllStatusTypes {
    id
    description
  }
}

mutation updateApplicationStatus($applicationId: Int!, $statusTypeId: Int!) {
  updateApplicationStatus(
    applicationId: $applicationId
    statusTypeId: $statusTypeId
  ) {
    message
    httpStatusCode
    success
  }
}
