query getApplicationById($applicationId: Int!) {
  getApplicationDetailsById(id: $applicationId) {
    data {
      id
      formId
      submissionId
    }
  }
}

query getSubmissionByApplicationId($applicationId: Int!) {
  getSubmissionByApplicationId(applicationId: $applicationId) {
    message
    httpStatusCode
    success
    data {
      id
      applicationId
      chefsFormId
      chefsSubmissionId
      chefsConfirmationId
      linkedConfirmationIds
      formData
      formSchema
      receivedAt
    }
  }
}
