query findSiteBySiteIdLoggedInUser($siteId: String!) {
  findSiteBySiteIdLoggedInUser(siteId: $siteId) {
    data {
      ...SiteDetails
      siteAssocs {
        siteIdAssociatedWith2 {
          ...SiteDetails
        }
      }
    }
  }
}

query findSiteBySiteIdForService($siteId: String!) {
  findSiteBySiteIdForService(siteId: $siteId) {
    message
    httpStatusCode
    success
    data {
      ...SiteDetails
      siteAssocs {
        siteIdAssociatedWith2 {
          ...SiteDetails
        }
      }
      landHistories {
        lutCode
        note
        srAction
        landUse {
          code
          description
        }
      }
    }
  }
}

fragment SiteDetails on Sites {
  id
  longdeg
  latdeg
  addrLine_1
  addrLine_2
  addrLine_3
  addrLine_4
  city
  commonName
  siteRiskCode
  whenCreated
  whenUpdated
}
