mutation updateStaffAssigned(
  $staffInput: [UpdateStaffAssignedDto!]!
  $applicationServiceTypeId: Int!
  $applicationId: Int!
) {
  updateStaffAssigned(
    staffInput: $staffInput
    applicationServiceTypeId: $applicationServiceTypeId
    applicationId: $applicationId
  ) {
    message
    httpStatusCode
    success
  }
}

mutation updateApplicationServiceType(
  $applicationId: Int!
  $serviceTypeId: Int
) {
  updateApplicationServiceType(
    applicationId: $applicationId
    serviceTypeId: $serviceTypeId
  ) {
    message
    httpStatusCode
    success
  }
}

mutation updateSecondaryServiceTypes(
  $applicationId: Int!
  $serviceTypeIds: [Int!]!
) {
  updateSecondaryServiceTypes(
    applicationId: $applicationId
    serviceTypeIds: $serviceTypeIds
  ) {
    message
    httpStatusCode
    success
  }
}

query getStaffAssignedByAppId($applicationId: Int!) {
  getStaffAssignedByAppId(applicationId: $applicationId) {
    data {
      applicationServiceTypeId
      staffList {
        id
        applicationId
        personId
        roleId
        startDate
        endDate
        currentCapacity
      }
    }
  }
}

query getAllActiveStaffMembers {
  getAllActiveStaffMembers {
    data {
      personId
      personFullName
      currentCapacity
    }
  }
}

query getAllActiveStaffMembersForApplicationServiceType($applicationServiceTypeId: Int!) {
  getAllActiveStaffMembersForApplicationServiceType(applicationServiceTypeId: $applicationServiceTypeId) {
    data {
      personId
      personFullName
      currentCapacity
    }
  }
}

query getStaffGroupedByRoleForServiceType($applicationServiceTypeId: Int!, $siteId: Int) {
  getStaffGroupedByRoleForServiceType(applicationServiceTypeId: $applicationServiceTypeId, siteId: $siteId) {
    data {
      roleId
      roleName
      roleAbbrev
      staff {
        personId
        personFullName
        currentCapacity
        appType
        endDate
        applicationId
        hasPermission
      }
    }
  }
}

query getApplicationServiceTypes {
  getApplicationServiceTypes {
    data {
      key
      value
    }
  }
}
