apiVersion: v1
kind: Secret
metadata:
  name: cats-backend
  namespace: e38158-prod
data:
  CATS_APPLICATION_URL: ''
  CATS_EMAIL_TEST_MODE: ''
  CATS_INTEGRATION_ENABLED: ''
  CATS_TEST_EMAIL_ADDRESS: ''
  CHEFS_EVENT_SUBSCRIPTION_TOKEN: ''
  CHEFS_API_KEY: ''
  CHES_CLIENT_ID: ''
  CHES_CLIENT_SECRET: ''
  CHES_EMAIL_FROM: ''
  CHES_EMAIL_URL: ''
  CHES_TOKEN_URL: ''
  CSSA_FORM_API_KEY: ''
  CSSA_FORM_ID: ''
  IR_FORM_API_KEY: ''
  IR_FORM_ID: ''
  KEYCLOAK_AUTH_URL: ''
  KEYCLOAK_CLIENT_ID: ''
  KEYCLOAK_REALM: ''
  KEYCLOAK_SECRET: ''
  KEYCLOAK_SITE_SERVICE_CLIENT_ID: ''
  KEYCLOAK_SITE_SERVICE_CLIENT_SECRET: ''
  KEYCLOAK_TOKEN_URL: ''
  NIR_FORM_API_KEY: ''
  NIR_FORM_ID: ''
  NOM_FORM_API_KEY: ''
  NOM_FORM_ID: ''
  SDS_FORM_API_KEY: ''
  SDS_FORM_ID: ''
  SITE_SERVICE_URL: ''
  VITE_COMS_API: ''
  VITE_COMS_BUCKET: ''
  VITE_COMS_OBJECT: ''
  VITE_S3_STORAGE_ACCESS_KEY_ID: ''
  VITE_S3_STORAGE_BUCKET: ''
  VITE_S3_STORAGE_ENDPOINT: ''
  VITE_S3_STORAGE_REGION: ''
  VITE_S3_STORAGE_SECRET_ACCESS_KEY: ''