apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: cats-backend
  namespace: e38158-prod
  labels:
    app.kubernetes.io/name: cats-backend
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: cats-backend
  minAvailable: 2
