
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: {{ .Chart.Name }}
  name: {{ .Chart.Name }}
data:
  KEYCLOAK_CLIENT: "{{tpl .Values.webclient .}}"
  APPLICATION_NAME: "{{tpl .Values.webname .}}"
  USER_ACCESS_PERMISSIONS: ''
  PUBLIC_WORKFLOW_ENABLED: "false"
  OPENTELEMETRY_SERVICE: "false"
  WEB_BASE_CUSTOM_URL: "{{tpl .Values.web.base_custom_url .}}"
  CUSTOM_THEME_URL: "{{tpl .Values.web.custom_theme_url .}}"
  ENABLE_FORMS_MODULE: "true"
  ENABLE_TASKS_MODULE: "true"
  ENABLE_DASHBOARDS_MODULE: "true"
  ENABLE_PROCESSES_MODULE: "true"
  ENABLE_APPLICATIONS_MODULE: "true"
  
---
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: {{ .Chart.Name }}-config.template
  name: {{ .Chart.Name }}-config.template
data:
  config.js: |-
    // runtime-config.js vars
      window["_env_"] =  {
        "NODE_ENV": "${NODE_ENV}",
        "REACT_APP_API_SERVER_URL": "${REACT_APP_API_SERVER_URL}",
        "REACT_APP_API_PROJECT_URL": "${REACT_APP_API_PROJECT_URL}", 
        "REACT_APP_BPM_URL": "${REACT_APP_BPM_URL}", 
        "REACT_APP_KEYCLOAK_CLIENT": "${REACT_APP_KEYCLOAK_CLIENT}", 
        "REACT_APP_WEB_BASE_URL": "${REACT_APP_WEB_BASE_URL}", 
        "REACT_APP_WEBSOCKET_ENCRYPT_KEY": "${REACT_APP_WEBSOCKET_ENCRYPT_KEY}", 
        "REACT_APP_KEYCLOAK_URL_REALM": "${REACT_APP_KEYCLOAK_URL_REALM}", 
        "REACT_APP_KEYCLOAK_URL": "${REACT_APP_KEYCLOAK_URL}",
        "REACT_APP_APPLICATION_NAME": "${REACT_APP_APPLICATION_NAME}",
        "REACT_APP_USER_ACCESS_PERMISSIONS": "${REACT_APP_USER_ACCESS_PERMISSIONS}",
        "REACT_APP_MT_ADMIN_BASE_URL": "${REACT_APP_MT_ADMIN_BASE_URL}",
        "REACT_APP_MT_ADMIN_BASE_URL_VERSION": "v1",
        "REACT_APP_MULTI_TENANCY_ENABLED": "${REACT_APP_MULTI_TENANCY_ENABLED}",
        "REACT_APP_KEYCLOAK_ENABLE_CLIENT_AUTH": "${REACT_APP_KEYCLOAK_ENABLE_CLIENT_AUTH}",
        "REACT_APP_CUSTOM_SUBMISSION_URL": "${REACT_APP_CUSTOM_SUBMISSION_URL}",
        "REACT_APP_CUSTOM_SUBMISSION_ENABLED": "${REACT_APP_CUSTOM_SUBMISSION_ENABLED}",
        "REACT_APP_DOCUMENT_SERVICE_URL": "${REACT_APP_DOCUMENT_SERVICE_URL}",
        "REACT_APP_DRAFT_ENABLED": "${REACT_APP_DRAFT_ENABLED}",
        "REACT_APP_DRAFT_POLLING_RATE": "${REACT_APP_DRAFT_POLLING_RATE}",
        "REACT_APP_CUSTOM_LOGOUT_URL": "${REACT_APP_CUSTOM_LOGOUT_URL}",
        "REACT_APP_CUSTOM_MAP_URL": "${REACT_APP_CUSTOM_MAP_URL}",
        "REACT_APP_EXPORT_PDF_ENABLED": "${REACT_APP_EXPORT_PDF_ENABLED}"

      }

