import { FormFieldType } from '../../../../components/input-controls/IFormField';
import {
  TableColumn,
  ColumnSize,
} from '../../../../components/table/TableColumn';

export const applicationResultColumns: TableColumn[] = [
  {
    id: 1,
    displayName: 'Application ID',
    active: true,
    graphQLPropertyName: 'id',
    groupId: 1,
    disabled: false,
    isDefault: true,
    sortOrder: 1,
    isChecked: true,
    displayType: { type: FormFieldType.Label, label: 'ID' },
    linkRedirectionURL: undefined,
    dynamicColumn: false,
    columnSize: ColumnSize.Default,
    stickyCol: false,
    customHeaderCss: '',
  },
  {
    id: 2,
    displayName: 'Site ID',
    active: true,
    graphQLPropertyName: 'siteId',
    groupId: 1,
    disabled: false,
    isDefault: true,
    sortOrder: 2,
    isChecked: true,
    displayType: { type: FormFieldType.Label, label: 'Site ID' },
    linkRedirectionURL: undefined,
    dynamicColumn: false,
    columnSize: ColumnSize.Default,
    stickyCol: false,
    customHeaderCss: '',
  },
  {
    id: 3,
    displayName: 'Site Address',
    active: true,
    graphQLPropertyName: 'siteAddress',
    groupId: 1,
    disabled: false,
    isDefault: true,
    sortOrder: 3,
    isChecked: true,
    displayType: { type: FormFieldType.Label, label: 'Site Address' },
    linkRedirectionURL: undefined,
    dynamicColumn: false,
    columnSize: ColumnSize.Default,
    stickyCol: false,
    customHeaderCss: '',
  },
  {
    id: 4,
    displayName: 'Application Type',
    active: true,
    graphQLPropertyName: 'applicationType',
    groupId: 1,
    disabled: false,
    isDefault: true,
    sortOrder: 4,
    isChecked: true,
    displayType: { type: FormFieldType.Label, label: 'Application Type' },
    linkRedirectionURL: undefined,
    dynamicColumn: false,
    columnSize: ColumnSize.Default,
    stickyCol: false,
    customHeaderCss: '',
  },
  {
    id: 5,
    displayName: 'Last Updated',
    active: true,
    graphQLPropertyName: 'lastUpdated',
    groupId: 1,
    disabled: false,
    isDefault: true,
    sortOrder: 5,
    isChecked: true,
    displayType: { type: FormFieldType.Label, label: 'Last Updated' },
    linkRedirectionURL: undefined,
    dynamicColumn: false,
    columnSize: ColumnSize.Default,
    stickyCol: false,
    customHeaderCss: '',
  },
  {
    id: 6,
    displayName: 'Status',
    active: true,
    graphQLPropertyName: 'status',
    groupId: 1,
    disabled: false,
    isDefault: true,
    sortOrder: 6,
    isChecked: true,
    displayType: { type: FormFieldType.Label, label: 'Status' },
    linkRedirectionURL: undefined,
    dynamicColumn: false,
    columnSize: ColumnSize.Default,
    stickyCol: false,
    customHeaderCss: '',
  },
  {
    id: 7,
    displayName: 'Priority',
    active: true,
    graphQLPropertyName: 'priority',
    groupId: 1,
    disabled: false,
    isDefault: true,
    sortOrder: 7,
    isChecked: true,
    displayType: { type: FormFieldType.Label, label: 'Priority' },
    linkRedirectionURL: undefined,
    dynamicColumn: false,
    columnSize: ColumnSize.Default,
    stickyCol: false,
    customHeaderCss: '',
  },
  {
    id: 8,
    displayName: 'View',
    active: true,
    graphQLPropertyName: 'url',
    groupId: 1,
    disabled: false,
    isDefault: true,
    sortOrder: 7,
    isChecked: true,
    displayType: {
      type: FormFieldType.Link,
      label: 'View',
      graphQLPropertyName: 'url',
      value: '',
      tableMode: true,
      href: '',
    },
    linkRedirectionURL: undefined,
    dynamicColumn: false,
    columnSize: ColumnSize.Default,
    stickyCol: false,
    customHeaderCss: '',
  },
];
