---
kind: Template
apiVersion: v1
metadata:
  name: "${API_NAME}-${ENV_TAG}-build-template"
  creationTimestamp: 
objects:
- kind: ImageStream
  apiVersion: v1
  metadata:
    name: "${API_NAME}"
- kind: BuildConfig
  apiVersion: v1
  metadata:
    name: "${API_NAME}-${ENV_TAG}-build"
    labels:
      app: "${API_NAME}-${ENV_TAG}-build"
  spec:
    completionDeadlineSeconds: 3600 # NOT WORKING?: Custom build time of 1hr, as builds are looong - STILL FAILS AFTER 30m
    resources:
      limits:
        cpu: "1500m" 
        memory: "4Gi"    
      requests:
        cpu: "500m"
        memory: "2Gi" 
    runPolicy: Serial
    source:
      type: Git
      git:
        uri: "${GIT_REPO_URL}"
        ref: "${GIT_REF}"
      contextDir: "${SOURCE_CONTEXT_DIR}"
    strategy:
      type: Docker
      dockerStrategy:
        dockerfilePath: "${DOCKER_FILE_PATH}"
        env:
        - name: ssh_prv_key
          valueFrom:
            secretKeyRef:
              name: ff-ee-deploy-key
              key: ssh-privatekey
        - name: ssh_pub_key
          valueFrom:
            secretKeyRef:
              name: ff-ee-deploy-key-pub
              key: ssh-privatekey
        - name: MF_FORMSFLOW_WEB_URL
          value: "https://forms-flow-web-ee-latest.apps.silver.devops.gov.bc.ca/forms-flow-web.js"
        - name: MF_FORMSFLOW_SERVICE_URL
          value: "https://forms-flow-microfrontends.aot-technologies.com/forms-flow-service@v5.2.1-alpha/forms-flow-service.gz.js"
        - name: MF_FORMSFLOW_ADMIN_URL
          value: "https://forms-flow-microfrontends.aot-technologies.com/forms-flow-admin@v5.2.1-alpha/forms-flow-admin.gz.js"
        - name: MF_FORMSFLOW_NAV_URL
          value: "https://forms-flow-nav-dev.apps.silver.devops.gov.bc.ca/forms-flow-nav.js"
        - name: MF_FORMSFLOW_THEME_URL
          value: "https://forms-flow-theme-dev.apps.silver.devops.gov.bc.ca/forms-flow-theme.js"
        - name: FORMIO_DEFAULT_PROJECT_URL
          value: "https://forms-flow-forms-e38158-dev.apps.silver.devops.gov.bc.ca"
        - name: KEYCLOAK_URL
          value: "https://epd-keycloak-dev.apps.silver.devops.gov.bc.ca"
        - name: FORMSFLOW_API_URL
          value: "https://forms-flow-api-e38158-dev.apps.silver.devops.gov.bc.ca"
        - name: BPM_API_URL
          value: "https://forms-flow-bpm-e38158-dev.apps.silver.devops.gov.bc.ca/camunda"
        - name: APPLICATION_NAME
          value: "formsflow.ai"
        - name: ENABLE_APPLICATION_ACCESS_PERMISSION_CHECK
          value: "false"
        - name: CUSTOM_SUBMISSION_URL
          value: "TODO"
        - name: CUSTOM_SUBMISSION_ENABLED
          value: "false"
        - name: EPD_IDP_LOGOUT_URL
          value: "https://logontest7.gov.bc.ca/clp-cgi/logoff.cgi?retnow=1&returl=https://epd-keycloak-dev.apps.silver.devops.gov.bc.ca/auth/realms/forms-flow-ai/protocol/openid-connect/logout?post_logout_redirect_uri=https://epd-frontend-dev.apps.silver.devops.gov.bc.ca/"
        - name: EPD_CUSTOM_MAP_URL
          value: "https://epd-frontend-dev.apps.silver.devops.gov.bc.ca/map"
    output:
      to:
        kind: ImageStreamTag
        name: "${API_NAME}:${ENV_TAG}"
parameters:
- name: API_NAME
  displayName: Name
  description: The name assigned to all of the resources defined in this template.
  required: true
  value: forms-flow-web-root-config
- name: ENV_TAG
  displayName: Environment name
  description: The name of the environment, in build names and image stream tags
  required: true
  value: dev
- name: GIT_REPO_URL
  displayName: Git Repo URL
  description: The URL to your GIT repo.
  required: true
  value: https://github.com/bcgov/nr-epd-digital-services
- name: GIT_REF
  displayName: Git Reference
  description: The git reference or branch.
  required: true
  value: dev
- name: SOURCE_CONTEXT_DIR
  displayName: Source Context Directory
  description: The source context directory.
  required: false
  value: forms-flow-ai/forms-flow-ai-ee/forms-flow-web-root-config
- name: DOCKER_FILE_PATH
  displayName: Docker File Path
  description: The path to the docker file defining the build.
  required: false
  value: "Dockerfile"