---
kind: Template
apiVersion: v1
metadata:
  annotations:
    description: Deployment template for a adjudication api service.
    tags: "${API_NAME}"
  name: "${API_NAME}-deploy"
objects:
- kind: DeploymentConfig
  apiVersion: v1
  metadata:
    name: "${API_NAME}"
    labels:
      app: "${API_NAME}"
      app-group: "${APP_GROUP}"
      template: "${API_NAME}-deploy"
  spec:
    strategy:
      type: Rolling
      rollingParams:
        updatePeriodSeconds: 1
        intervalSeconds: 1
        timeoutSeconds: 600
        maxUnavailable: 25%
        maxSurge: 25%
        # pre:
        #   failurePolicy: Abort
          # execNewPod:
            # command:
            # - "/bin/bash"
            # - "-c"
            # - "python manage.py db upgrade"
            # containerName: "${API_NAME}"
    triggers:
    - type: ImageChange
      imageChangeParams:
        automatic: true
        containerNames:
        - "${API_NAME}"
        from:
          kind: ImageStreamTag
          namespace: "${IMAGE_NAMESPACE}"
          name: "${IMAGE_STREAM_NAME_FULL}"
    - type: ConfigChange
    replicas: 1
    test: false
    selector:
      app: "${API_NAME}"
      deploymentconfig: "${API_NAME}"
    template:
      metadata:
        labels:
          app: "${API_NAME}"
          app-group: "${APP_GROUP}"
          deploymentconfig: "${API_NAME}"
          template: "${API_NAME}-deploy"
          role: api
      spec:
        containers:
        - name: "${API_NAME}"
          image: "${API_NAME}"
          imagePullPolicy: Always
          env:
            - name: MF_FORMSFLOW_WEB_URL
              value: "https://forms-flow-web-ee-latest.apps.silver.devops.gov.bc.ca/forms-flow-web.js"
            - name: MF_FORMSFLOW_SERVICE_URL
              value: "https://forms-flow-microfrontends.aot-technologies.com/forms-flow-service@v5.2.1-alpha/forms-flow-service.gz.js"
            - name: MF_FORMSFLOW_ADMIN_URL
              value: "https://forms-flow-microfrontends.aot-technologies.com/forms-flow-admin@v5.2.1-alpha/forms-flow-admin.gz.js"
            - name: MF_FORMSFLOW_NAV_URL
              value: "https://forms-flow-nav-dev.apps.silver.devops.gov.bc.ca/forms-flow-nav.js"
            - name: MF_FORMSFLOW_THEME_URL
              value: "https://forms-flow-theme-dev.apps.silver.devops.gov.bc.ca/forms-flow-theme.js"
            - name: FORMIO_DEFAULT_PROJECT_URL
              value: "https://forms-flow-forms-e38158-dev.apps.silver.devops.gov.bc.ca"
            - name: KEYCLOAK_URL
              value: "https://epd-keycloak-dev.apps.silver.devops.gov.bc.ca"
            - name: FORMSFLOW_API_URL
              value: "https://forms-flow-api-e38158-dev.apps.silver.devops.gov.bc.ca"
            - name: BPM_API_URL
              value: "https://forms-flow-bpm-e38158-dev.apps.silver.devops.gov.bc.ca/camunda"
            - name: APPLICATION_NAME
              value: "formsflow.ai"
            - name: ENABLE_APPLICATION_ACCESS_PERMISSION_CHECK
              value: "false"
            - name: CUSTOM_SUBMISSION_URL
              value: "TODO"
            - name: CUSTOM_SUBMISSION_ENABLED
              value: "false"
            - name: EPD_IDP_LOGOUT_URL
              value: "https://logontest7.gov.bc.ca/clp-cgi/logoff.cgi?retnow=1&returl=https://epd-keycloak-dev.apps.silver.devops.gov.bc.ca/auth/realms/forms-flow-ai/protocol/openid-connect/logout?post_logout_redirect_uri=https://epd-frontend-dev.apps.silver.devops.gov.bc.ca/"
            - name: EPD_CUSTOM_MAP_URL
              value: "https://epd-frontend-dev.apps.silver.devops.gov.bc.ca/map"
          ports:
          - containerPort: 8080
            protocol: TCP
          resources:
            requests:
              cpu: "50m"
              memory: "250Mi"
            limits:
              cpu: "150m"
              memory: "500Mi"
          terminationMessagePath: "/dev/termination-log"
          terminationMessagePolicy: File
          imagePullPolicy: Always
        restartPolicy: Always
        terminationGracePeriodSeconds: 30
        dnsPolicy: ClusterFirst
        securityContext: {}
        schedulerName: default-scheduler
- kind: Service
  apiVersion: v1
  metadata:
    name: "${API_NAME}"
    creationTimestamp: 
    labels:
      app: "${API_NAME}"
      app-group: "${APP_GROUP}"
      template: "${API_NAME}-deploy"
  spec:
    ports:
    - name: 8080-tcp
      protocol: TCP
      port: 8080
      targetPort: 8080
    selector:
      deploymentconfig: "${API_NAME}"
    type: ClusterIP
    sessionAffinity: None
   
  # status:
  #   loadBalancer: {}
- kind: Route
  apiVersion: v1
  metadata:
    name: "${API_NAME}"
    labels:
      app: "${API_NAME}"
      app-group: "${APP_GROUP}"
      template: "${API_NAME}-deploy"
  spec:
    to:
      kind: Service
      name: "${API_NAME}"
      weight: 100
    port:
      targetPort: 8080-tcp
    tls:
      termination: edge
    wildcardPolicy: None
    host: "${API_NAME}-${TAG_NAME}.apps.silver.devops.gov.bc.ca"
parameters:
- name: API_NAME
  displayName: Name
  description: The name assigned to all of the OpenShift resources associated to the
    server instance.
  required: true
  value: forms-flow-web-root-config
- name: APP_GROUP
  displayName: App Group
  description: The name assigned to all of the deployments in this project.
  required: true
  value: epd
- name: IMAGE_NAMESPACE
  displayName: Image Namespace
  required: true
  description: The namespace of the OpenShift project containing the imagestream for
    the application.
  value: e38158-tools
- name: TAG_NAME
  displayName: Environment TAG name
  description: The TAG name for this environment, e.g., dev, test, prod
  required: true
  value: dev
- name: IMAGE_STREAM_NAME_FULL
  displayName: Full image stream name (eg "frontend:dev")
  description: Includes ImageStream name and tag
  required: true
  value: forms-flow-web-root-config:dev