apiVersion: v1
kind: Pod
metadata:
  name: temp-pod
spec:
  containers:
    - name: uploader
      image: alpine
      command: ['/bin/sh', '-c', 'sleep 3600']
      volumeMounts:
        - name: sql-volume
          mountPath: /mnt/sql
      resources:
        requests:
          cpu: '40m'
          memory: '64Mi'
  volumes:
    - name: sql-volume
      persistentVolumeClaim:
        claimName: nr-cats-dbdump-sql
