{{- if .Values.backend.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "backend.fullname" . }}
  labels:
    {{- include "backend.labels" . | nindent 4 }}
  {{- if and .Values.backend.ingress .Values.backend.ingress.annotations }}
  {{- with .Values.backend.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- end }}
spec:
  ingressClassName: openshift-default
  rules:
    - host: {{ lower (include "backend.fullname" .) }}.{{ .Values.global.domain }}
      http:
        paths:
          - path: /
            pathType: ImplementationSpecific
            backend:
              service:
                name: {{ include "backend.fullname" . }}
                port:
                  number: 80
{{- end }}
