{{- if .Values.backend.enabled }}
{{- if and .Values.backend.pdb  .Values.backend.pdb.enabled }}
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "backend.fullname" . }}
  labels:
    {{- include "backend.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "backend.selectorLabels" . | nindent 6 }}
  minAvailable: {{ .Values.backend.pdb.minAvailable }}
{{- end }}
{{- end }}
