name: CATS PR

on:
  pull_request:
    # TODO: Re-enable and test the 'types', for now just removing it, as it's blocking from opening PR. Perhaps there's a better value to insert into array.
    # types: [opened, synchronize, reopened, ready_for_review] # ready for review is not included by default, More than one activity type triggers this event. For information about each activity type, see "Webhook events and payloads." By default, a workflow only runs when a pull_request event's activity type is opened, synchronize, or reopened. To trigger workflows by different activity types, use the types keyword. For more information, see "Workflow syntax for GitHub Actions."
    branches:
      - srs-605-cats-cicd
      #- srs-605 #test branch
    # paths:
    #   - 'backend/cats/**'
    #   - 'cats-frontend/**'  
  # TODO: Delete below when done active dev, just left in for dev purpoess.
  push:
    branches:
      - srs-605-cats-cicd

concurrency:
  # Cancel in progress for PR open and close
  # group: ${{ github.event.number }}
  group: ${{ github.event.pull_request.number || github.run_id }}
  cancel-in-progress: true

jobs:
  # https://github.com/bcgov-nr/action-builder-ghcr
  builds:
    name: Builds
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        package: [backend, backend-migration, cats-frontend ]
        include:
          - package: backend
            build_file: ./backend/cats/Dockerfile
            build_context: backend/cats
          - package: backend-migration
            build_file: ./backend/cats/Dockerfile-migrations-openshift
            build_context: backend-migration
          - package: cats-frontend
            build_file: ./cats-frontend/Dockerfile
            build_context: cats-frontend
    timeout-minutes: 10
    steps:
      - uses: bcgov-nr/action-builder-ghcr@v2.2.0
        with:
          package: ${{ matrix.package }}
          # tag: ${{ github.event.number }}
          tag: ${{ github.event.pull_request.number || github.run_id }}
          tag_fallback: latest
          triggers: ('${{ matrix.package }}/')
          build_file: ${{ matrix.build_file }}
          build_context: ${{ matrix.build_context }}

  # TODO - Re-enable this, just temporarily out so we can verify if issue is with this step or deploys step below
  deploy_db:
    name: Deploys Database
    if: ${{ ! github.event.pull_request.draft }}
    uses: ./.github/workflows/.dbdeployer.yml
    secrets: inherit
    with:
      triggers: ('charts/crunchy/')
      values: 'values-dev.yaml'
      app_values:  'values-pr.yaml' # PR specific values file.
    # https://github.com/bcgov/quickstart-openshift-helpers
  deploys:
    name: Deploys
    if: ${{ ! github.event.pull_request.draft }}
    needs: [builds, deploy_db]
    # needs: [builds]
    uses: ./.github/workflows/.deployer.yml
    secrets: inherit
    with:
      triggers: ('backend/cats/' 'cats-frontend/' 'charts/' '.github/workflows/')
      values: 'values-pr.yaml' # PR specific values file.
      # db_user: cats-${{ github.event.number }}
      db_user: cats-${{ github.event.pull_request.number || github.run_id }}
      timeout-minutes: 20

  results:
    name: PR Results
    needs: [builds, deploys]
    if: always()
    runs-on: ubuntu-24.04
    steps:
      - if: contains(needs.*.result, 'failure')
        run: echo "At least one job has failed." && exit 1
      - run: echo "Success!"