name: Manual Deployment to PROD From Main.
#This workflow will just tag docker image from test to the tag number and deploy it to PROD.

on:
  workflow_dispatch:
    inputs:
      RELEASE_VERSION:
        required: true
        description: The Tag release to PROD.

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  builds:
    name: Builds
    uses: ./.github/workflows/_build.yml
    strategy:
      matrix:
        component: [ backend, frontend ]
        include:
          - component: backend
            triggers: ('backend/')
          - component: frontend
            triggers: ('frontend/')
    secrets:
      gh_token: ${{ secrets.GITHUB_TOKEN }}
    with:
      component: ${{ matrix.component }}
      img_build: ${{ inputs.RELEASE_VERSION }}
      img_fallback: "test" # The test image will be tagged with prod release version as in input.
      triggers: ${{ matrix.triggers }}


  deploys:
    name: Deploys
    needs:
      - builds
    # If any of the previous created a build, then deploy
    if: contains(needs.*.outputs.build, 'true')
    uses: ./.github/workflows/_deploy.yml
    strategy:
      matrix:
        component: [backend, database, frontend]
        include:
          - component: database
            overwrite: false
            template_file: .github/openshift/deploy.database.yml
            template_vars: -p DB_PVC_SIZE=500Mi
          - component: backend
            overwrite: true
            template_file: .github/openshift/deploy.backend.yml
            template_vars: -p PROMOTE=${{ github.repository }}/backend -p CONTAINER_PORT=3000 -p ENV=prod -p IMAGE_TAG=${{ inputs.RELEASE_VERSION }} -p MIN_REPLICAS=3 -p MAX_REPLICAS=7
          - component: frontend
            overwrite: true
            template_file: .github/openshift/deploy.frontend.yml
            template_vars: -p PROMOTE=${{ github.repository }}/frontend -p CONTAINER_PORT=3000 -p ENV=prod -p IMAGE_TAG=${{ inputs.RELEASE_VERSION }} -p MIN_REPLICAS=3 -p MAX_REPLICAS=7
    secrets:
      oc_namespace: ${{ secrets.OC_NAMESPACE }}
      oc_server: ${{ secrets.OC_SERVER }}
      oc_token: ${{ secrets.OC_TOKEN }}
    with:
      environment: prod
      component: ${{ matrix.component }}
      overwrite: ${{ matrix.overwrite }}
      template_file: ${{ matrix.template_file }}
      template_vars: ${{ matrix.template_vars }}
  tag:
    name: Create The Production Release Tag
    runs-on: ubuntu-22.04
    environment: prod
    steps:
      - uses: rickstaa/action-create-tag@v1
        name: Create Release Tag in Git
        with:
          tag: "release/${{ inputs.RELEASE_VERSION }}"
          message: "Release version ${{ inputs.RELEASE_VERSION }}"
