name: Continuous Integration And Deployment On Push to Tools
#This is only for testing purpose and will be deleted in future.
on:
  workflow_dispatch: 
  push:
    branches:
    #  - 'dev
       - 'feat/srs-25-etl-deploy' #test
    paths:
      - 'etl/**'
      - '.github/workflows/ci-cd-debezium-tools.yaml'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  builds:
    name: Builds
    uses: ./.github/workflows/_build.yml
    strategy:
      matrix:
        component: [ etl/debezium-jdbc, etl/debezium-postgis/15-3.3 ]
        include:
          - component:etl/debezium-jdbc 
            triggers: ('etl/debezium-jdbc/')
         - component: etl/debezium-postgis/15-3.3 
            triggers: ('etl/debezium-postgis/15-3.3/')
    secrets:
      gh_token: ${{ secrets.GITHUB_TOKEN }}
    with:
      component: ${{ matrix.component }}
      img_build: "tools"
      img_fallback: tools
      triggers: ${{ matrix.triggers }}
