name: Deploy CATS to TEST

on:
  push:
    branches:
      - dev 
      - feat/CATS-test

concurrency:
  group: test
  cancel-in-progress: false

jobs:
  # https://github.com/bcgov-nr/action-builder-ghcr
  builds:
    name: Builds
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        package: [backend, backend-migration, cats-frontend]
        include:
          - package: backend
            build_file: ./backend/cats/Dockerfile
            build_context: backend/cats
          - package: backend-migration
            build_file: ./backend/cats/Dockerfile-migrations-openshift
            build_context: backend/cats
          - package: cats-frontend
            build_file: ./cats-frontend/Dockerfile
            build_context: cats-frontend
    timeout-minutes: 10
    steps:
      - uses: bcgov-nr/action-builder-ghcr@v2.2.0
        with:
          package: ${{ matrix.package }}
          # tag: ${{ github.event.number }}
          tag: test
          tag_fallback: latest
          triggers: ('${{ matrix.package }}/')
          build_file: ${{ matrix.build_file }}
          build_context: ${{ matrix.build_context }}

          
  deploy_db:
    name: Deploys Database (test)
    uses: ./.github/workflows/.dbdeployer.yml
    secrets: inherit
    with:
      triggers: ('charts/crunchy/' '.github/workflows/cats-pr-open.yml')
      # triggers: ('charts/crunchy/')
      values: 'values-dev.yaml'
      app_values:  'values-test.yaml' 
      environment: test
    # https://github.com/bcgov/quickstart-openshift-helpers
  deploys:
    name: Deploys (test)
    needs: [builds, deploy_db]
    uses: ./.github/workflows/.deployer.yml
    secrets: inherit
    with:
      triggers: ('backend/cats/' 'cats-frontend/' 'charts/' '.github/workflows/')
      values: 'values-test.yaml'
      redirect_uri: https://logontest7.gov.bc.ca/clp-cgi/logoff.cgi?retnow=1&returl=https://epd-keycloak-test.apps.silver.devops.gov.bc.ca/auth/realms/forms-flow-ai/protocol/openid-connect/logout?post_logout_redirect_uri=https://nr-epd-digital-services-${{ github.event.pull_request.number}}-frontend.apps.silver.devops.gov.bc.ca/
      db_user: cats-test
      timeout-minutes: 20
      environment: test
  
  results:
    name: PR Results
    needs: [builds, deploys]
    if: always()
    runs-on: ubuntu-24.04
    steps:
      - if: contains(needs.*.result, 'failure')
        run: echo "At least one job has failed." && exit 1
      - run: echo "Success!"