name: Deploy Frontend to Test env

on:
  push:
    branches:
      - main
    paths:
      - "frontend/**"
  workflow_dispatch:
    inputs:
      environment:
        description: "Environment (dev/test/prod)"
        required: true
        default: "test"

defaults:
  run:
    shell: bash
    working-directory: ./frontend

env:
  APP_NAME: "frontend"
  TAG_NAME: "test"

jobs:
  frontend-cd-by-push:
    runs-on: ubuntu-20.04

    if: github.event_name == 'push' && github.repository == 'bcgov/nr-epd-digital-services'
    environment:
      name: "test"

    steps:
      - uses: actions/checkout@v2

      - name: Login Openshift
        shell: bash
        run: |
          oc login --server=${{secrets.OC_SERVER}} --token=${{secrets.OC_TOKEN}}

      - name: Tools project
        shell: bash
        run: |
          oc project ${{ secrets.OC_NAMESPACE_NAMEPLATE }}-tools

      - name: Build from main branch
        shell: bash
        run: |
          oc patch bc/frontend-build -p '{"spec":{"source":{"git":{"ref":"main"}}}}'

      - name: Start Build Openshift
        shell: bash
        run: |
          oc start-build frontend-build --wait

      - name: Tag+Deploy for TEST
        shell: bash
        run: |
          oc tag frontend:latest frontend:test

      # - name: Watch new rollout (trigger by image change in Openshift)
      #   shell: bash
      #   run: |
      #     oc rollout status dc/${{ env.APP_NAME }} -n ${{ secrets.OPENSHIFT4_FRONTEND_REPOSITORY }}-${{ env.TAG_NAME }} -w

      # - name: Rocket.Chat Notification
      #   uses: RocketChat/Rocket.Chat.GitHub.Action.Notification@master
      #   if: failure()
      #   with:
      #     type: ${{ job.status }}
      #     job_name: "*Auth Web Built and Deployed to ${{env.TAG_NAME}}*"
      #     channel: "#registries-bot"
      #     url: ${{ secrets.ROCKETCHAT_WEBHOOK }}
      #     commit: true
      #     token: ${{ secrets.GITHUB_TOKEN }}