name: Dev Merge - Deploy to TEST

on:
  push:
    branches:
      - srs-605

concurrency:
  # Cancel in progress for PR open and close
  group: test
  cancel-in-progress: false

jobs:
  get-pr-info:
    runs-on: ubuntu-24.04
    outputs:
      pr: ${{ steps.vars.outputs.pr }}
    steps:
      - id: vars
        uses: bcgov-nr/action-get-pr@v0.0.1
      - name: Echo PR number
        run: |
          echo "PR: ${{ steps.vars.outputs.pr }}"

  deploy_db:
    name: Deploys Database
    uses: ./.github/workflows/.dbdeployer.yml
    secrets: inherit
    with:
      environment: test
      values: 'values-test.yaml'
      app_values: 'values.yaml' # TEST env specific values file for the APP
  deploys:
    name: Deploys to TEST
    uses: ./.github/workflows/.deployer.yml
    secrets: inherit
    needs: [get-pr-info, deploy_db]
    with:
      environment: test
      tag:  '${{ needs.get-pr-info.outputs.pr }}'
      values: 'values.yaml' # TEST env specific values file


  schemaspy:
    name: Schemaspy
    uses: ./.github/workflows/.schema-spy.yml
    secrets: inherit
    needs: [deploys]
    with:
      tag: test