name: PR Validate

on:
  pull_request:
    types: [edited, opened, synchronize, reopened, ready_for_review]

concurrency:
  group: ${{ github.workflow }}-edit-${{ github.event.number }}
  cancel-in-progress: true

jobs:
  validate:
    name: Validate PR
    if: (! github.event.pull_request.draft)
    uses: bcgov/quickstart-openshift-helpers/.github/workflows/.pr-validate.yml@v0.8.0
    with:
      markdown_links: |
        - [Backend](https://${{ github.event.repository.name }}-${{ github.event.number }}-backend.apps.silver.devops.gov.bc.ca)
        - [Frontend](https://${{ github.event.repository.name }}-${{ github.event.number }}-frontend.apps.silver.devops.gov.bc.ca)

  results:
    name: Validate Results
    if: always()
    needs: [validate]
    runs-on: ubuntu-24.04
    steps:
      - run: echo "Success!"
