name: Prettier Format

on:
  pull_request:
    branches: [dev]

jobs:
  prettier:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: cats-frontend

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: ${{ github.head_ref }}
          persist-credentials: false

      - name: Prettify code
        uses: creyD/prettier_action@v4.3
        with:
          # working_directory: /home/runner/work/nr-epd-digital-services/nr-epd-digital-services/cats-frontend
          # prettier_options: --check /home/runner/work/nr-epd-digital-services/nr-epd-digital-services/cats-frontend/src/**/*.{js,ts,jsx,tsx,json,css}
          prettier_options: --check ./**/*.{js,ts,jsx,tsx,json,css}
          # only_changed: True
          dry: True