name: Scheduled

on:
  schedule: [cron: "0 11 * * 6"] # 3 AM PST = 12 PM UDT, Saturdays
  workflow_dispatch:
  workflow_call:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  #TODO add schemaspy, https://github.com/bcgov/quickstart-openshift/blob/main/.github/workflows/scheduled.yml#L54-L95

  # Run sequentially to reduce chances of rate limiting
  zap_scan:
    runs-on: ubuntu-latest
    name: ZAP Scans
    env:
      DOMAIN: apps.silver.devops.gov.bc.ca
      PREFIX: ${{ github.event.repository.name }}-test
    steps:
      - name: ZAP Scan - Backend
        uses: zaproxy/action-full-scan@v0.11.0
        with:
          allow_issue_writing: true
          artifact_name: "zap_backend"
          cmd_options: "-a"
          issue_title: "ZAP: Backend"
          target: https://${{ env.PREFIX }}-backend.${{ env.DOMAIN }}

      - name: ZAP Scan - Frontend
        uses: zaproxy/action-full-scan@v0.11.0
        with:
          allow_issue_writing: true
          artifact_name: "zap_frontend"
          cmd_options: "-a"
          issue_title: "ZAP: Frontend"
          target: https://${{ env.PREFIX }}-frontend.${{ env.DOMAIN }}
